## Site Meta ##
# The title of the website.
title: "Happy 6!!!!"
# The description of the website
description: "A Jekyll theme for photographers and photo bloggers."
# Keywords/tags for you site.
keywords: "lens, jeykll-lens, jekyll, theme, jekyll-theme, photography, blog, photography-blog, photo-blog"
# Your copyright message.
copyright: "Copyright ranis mans"

## Site Configurations ##
# 1st heading of the site.
header: "Happy 6 Rani!!"
# 2nd heading/sub heading of the website.
subheader: "From ur Computer Science mansðŸ˜­"
# A description/bio of the website.
bio: "A photo album of some of my fav mems with you :)"
social:
  # Your Twitter username.
  twitter_username: ""
  # Your Facebook username.
  facebook_username: ""
  # Your Instagram username.
  instagram_username: ""
  # GitHub username.
  github_username: ""
  # Your email address.
  email: ""

## Gallery Configuration ##
# If you modify this, also modify the `default.scope.path` key below.
gallery_dir: "gallery"
# Any valid value of "background-position" CSS attribute.
image_position: "left center"

## Jekyll Configuration ##
defaults:
 - scope:
    # Should be same as the `gallery_dir` key above.
    path: "gallery"
   values:
    image: true

gallery:  
  - name: "image1.jpeg"
    message: "4/15/2021 - Asheville!! Flat tire, pelicans, a waterfall, and Chai pani and a beautiful sunset with my beautiful girl"
  - name: "image2.JPG"
    message: "5/6/2021 - Zoo! The noises you made feeding those animals was so funnyðŸ˜‚ then the strawberry patch and choco strawberries :)"
  - name: "image3.JPG"
    message: "6/2/2021 - CLT! The first time I visited you in Charlotte and I had a wonderful day w my Rani in the Rani City"
  - name: "image4.jpeg"
    message: "6/27/2021 - Seattle! I really can't pick just oneðŸ˜­ There were too many amazing memories from that trip. \n Getting soaked in this waterfall with you was absolutely amazing"
  - name: "image11.jpeg"
    message: "8/20/2021 - Lafayette Village! Our first date after I came back from Seattle, and you got drunk off one drinkðŸ˜‚ \nand we went to a drag show at legends"
  - name: "image5.JPG"
    message: "9/7/2021 - :) The day I made u my girlfriend. I also got you a really bad cava bowlðŸ˜­"
  - name: "image6.JPG"
    message: "9/11/2021 - VA Beach! We Banana Boated!! then got LITTYYY on the beach togetherðŸ˜˜"
  - name: "image7.jpeg"
    message: "9/24/2021 - Hot Air balloon festival! Then we got Thai foodðŸ˜‚"
  - name: "image8.JPG"
    message: "10/7/21 - One Month :) We went to Cilantro then we went to Board games!! and then you gave me a fashion showðŸ˜˜"
  - name: "image9.JPG"
    message: "10/15/21 - My BDay party! My beautful Rani took me on an incredible date and then threw me the best Bday party everâ¤ï¸ï¸"
  - name: "image10.jpeg"
    message: "10/22/21 - DC! We had an incredible time lime scootering around DC and went to HASAN and got littyyyyðŸ˜˜"
  - name: "image14.JPG"
    message: "12/4/21 - Grad pics n Picnic! I met sharks and we took this amazing picture"
  - name: "image12.jpeg"
    message: "12/7/21 - Three months! We went Olive garden then to the Chinese Lantern Festival and we got Spiked HOT COCOOOO"
  - name: "image13.jpeg"
    message: "12/28/21 - Carowinds! I visited CLT again and we got Hawkers! and then Acai bowl then PREGAMED carowinds and almost didnt make it out of the carðŸ˜˜"
  - name: "image15.jpeg"
    message: "1/12/22 - RV trip :) One of the best days I spent with youâ¤ï¸ï¸ litty alllll day and date night n hot tub i wish that day lasted foreverðŸ˜­"
  - name: "image16.jpeg"
    message: "1/28/22 - The last time I got to see uðŸ˜­ We did minigolffff and then you tucked me in and kissed me on the foreheadðŸ˜˜"
  - name: "image17.PNG"
    message: "2/14/22 - Vdayâ¤ï¸ An amazing virtual date with my beautiful girlie. The first of manyðŸ˜˜ Next-> More virtual dates then COSTA RICAAA"